version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"

updates:
  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: all
    patterns:
      - "*"
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7
      include:
        - "*"

  - package-ecosystem: npm
    directory: /
    multi-ecosystem-group: all
    patterns:
      - "*"
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 1
      include:
        - "*"
