name: Licensed CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v4
        with:
          cache: npm
          node-version: 20

      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: ruby
          bundler-cache: true

      - uses: github/setup-licensed@be11bcbb82e3140b6cf260e647c3efeeca8fcefd # v1
        with:
          version: "4.x"

      - run: npm install

      - run: npm run test

      - name: Run licensed-ci
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: push
