name: Licensed CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          cache: npm
          node-version: 20

      - uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1.307.0
        with:
          ruby-version: ruby
          bundler-cache: true

      - uses: github/setup-licensed@be11bcbb82e3140b6cf260e647c3efeeca8fcefd # v1
        with:
          version: "4.x"

      - run: npm install

      - run: npm run test

      - name: Run licensed-ci
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: push
