name: "Test"
on: pull_request
permissions:
  contents: read

jobs:
  npm_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20.x ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node }}

    - run: npm install

    # install licensed
    - uses: ruby/setup-ruby@8711a86ab6f9aa72890da4123b2ef7283b6b22b6
      with:
        ruby-version: ruby
    - uses: github/setup-licensed@v1
      with:
        version: '4.x'

    - run: npm run test
