name: "Test"
on: pull_request
permissions:
  contents: read

jobs:
  npm_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20.x ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node }}

    - run: npm install

    # install licensed
    - uses: ruby/setup-ruby@eaecf785f6a34567a6d97f686bbb7bccc1ac1e5c
      with:
        ruby-version: ruby
    - uses: github/setup-licensed@v1
      with:
        version: '4.x'

    - run: npm run test
